### ISSUE TITLE
Viewer stays on external screen after you unplug it.

### ISSUE THREAD

**Issue by jordy-u** [hereafter/camera-preview#1]
When a monitor is disconnected, the app sometimes stays on that screen and there is no way to get it back, except for plugging the old monitor back in, if you have it.

The `Windows + Arrow button` trick does not work in frameless mode.

**How to fix this**
1. Open the Windows Start menu
2. Browse for the Camera Preview app
3. Right click --> more --> App Settings
4. Reset
5. Now it is back on the primary screen again

Is there a more user friendly way to fix this? It might be more a Windows problem than a problem with your application, though.

Thanks for making this app!

**Comment by hereafter** [comment]
Hi, thanks for reporting
I will add a watchdog to see if previous/current window is within reachable monitors

**Comment by hereafter** [comment]
please check the store 1.1 version to see if the issue is fixed

**Comment by jordy-u** [comment]
Hey @hereafter. Thank you very much for the fix, it works! I tested it this way:
1. Putting the viewer on screen B and close it.
2. Disconnect screen B.
3. Start Camera Preview again.
Result: The viewer automatically starts at the center of my primary screen.

It also resets to the center when it's partly off the screen before closing, which is nice.
